name: Daily FBref Scraper

# Triggers: daily at 02:00 UTC, or manual trigger
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 lxml

      # Step 4: Run the FBref scraper
      - name: Run scraper
        run: python scrape_fbref.py

      # Step 5: Commit generated CSV files back to the repo
      - name: Commit CSV files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if ls *.csv 1> /dev/null 2>&1; then
            git add *.csv
            git commit -m "Daily scrape update" || echo "No changes to commit"
            git push
          else
            echo "No CSV files to commit"
          fi
