name: Daily FBref Scraper

on:
  schedule:
    - cron: "0 2 * * *" # every day at 02:00 UTC
  workflow_dispatch: # allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install footballwebscraper pandas

      - name: Run scraper
        run: python scrape.py

      - name: Commit CSV files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.csv
          git commit -m "Daily scrape update" || echo "No changes"
          git push
